users/routes.py
import csv
import io
import json

from bson import ObjectId
import gridfs
import openpyxl
from flask import Blueprint, render_template, request, url_for, redirect, flash, session, Response

from flask_login import login_user, current_user, logout_user, login_required

import constants
from config import mongo
from users import utils
from users.forms import LoginForm, ManagerForm, EmployeeForm, PermissionForm, RoleForm
from users.user import User


login_bp = Blueprint(
    'login_bp', __name__,
    template_folder='templates'
)

export_bp = Blueprint(
    'export_bp', __name__,
    url_prefix="/export",
    template_folder='templates'
)

roles_bp = Blueprint(
    'roles_bp', __name__,
    url_prefix="/role",
    template_folder='templates'
)

permissions_bp = Blueprint(
    'permissions_bp', __name__,
    url_prefix="/permission",
    template_folder='users/templates'
)

admin_bp = Blueprint(
    'admin_bp', __name__,
    url_prefix="/admin",
    template_folder='users/templates'
)

employee_bp = Blueprint(
    'employee_bp', __name__,
    url_prefix="/employee",
    template_folder='users/templates'
)

manager_bp = Blueprint(
    'manager_bp', __name__,
    url_prefix="/manager",
    template_folder='users/templates'
)


@admin_bp.route('/dashboard', methods=('GET', 'POST'))
@utils.role_required(["admin"])
def admin_dashboard():
    employees = session.get('filtered_employees')
    if employees is None:
        employees = utils.get_employees()
    session.pop('filtered_employees', None)
    return render_template(
        'admin_dashboard.html',
        managers=utils.get_managers(),
        employees=employees,
        permissions=utils.get_permissions(),
        roles=utils.get_roles(),
        department_choices=constants.department_choices,
        designation_choices=constants.designation_choices)


@roles_bp.route('/create', methods=('GET', 'POST'))
@utils.role_required(["admin"])
def create_role():
    form = RoleForm()
    form.permissions.choices = [(permission.get('_id'), permission.get('name')) for permission in utils.get_permissions()]
    if request.method == 'POST':
        name = form.name.data
        existing_role = mongo.db.roles.find_one({'name': name})
        if existing_role:
            flash('Role name must be unique.', 'danger')
        else:
            permissions_ids = form.permissions.data
            mongo.db.roles.insert_one({'name': name, 'permissions_ids': [ObjectId(each) for each in permissions_ids]})
            return redirect(url_for('admin_bp.admin_dashboard'))
    return render_template('role_create.html', form=form)


@roles_bp.route('/delete/<role_id>', methods=('GET', 'POST'))
@utils.role_required(["admin"])
def delete_role(role_id):
    role_id = ObjectId(role_id)
    mongo.db.roles.delete_one({'_id': role_id})
    cursor_obj = mongo.db.users.find({"role_id": role_id}, {"_id": 1})
    [mongo.db.users.update_many({"manager": each["_id"]}, {"$set": {"manager": None}}) for each in cursor_obj]
    mongo.db.users.update_many(
        {"role_id": role_id},
        {"$set": {"role_id": None}}
    )
    return redirect(url_for('admin_bp.admin_dashboard'))


@permissions_bp.route('/create', methods=('GET', 'POST'))
@utils.role_required(["admin"])
def create_permission():
    form = PermissionForm()
    if form.validate_on_submit():
        name = request.form['name']
        existing_permission = mongo.db.permissions.find_one({'name': name})
        if existing_permission:
            flash('Permission name must be unique.', 'danger')
        else:
            mongo.db.permissions.insert_one({'name': name})
            return redirect(url_for('admin_bp.admin_dashboard'))
    return render_template('permission_create.html', form=form)


@permissions_bp.route('/delete/<permission_id>', methods=('GET', 'POST'))
@utils.role_required(["admin"])
def delete_permission(permission_id):
    mongo.db.roles.update_many({}, {"$pull": {"permissions_ids": permission_id}})
    mongo.db.permissions.delete_one({'_id': ObjectId(permission_id)})
    return redirect(url_for('admin_bp.admin_dashboard'))


@manager_bp.route('/dashboard', methods=('GET', 'POST'))   # Focus here
@utils.role_required(["manager"])
def manager_dashboard():
    employees = session.get('filtered_employees')
    if employees is None:
        employees = utils.get_employees()
    session.pop('filtered_employees', None)
    return render_template(
        'manager_dashboard.html',
        employees=employees, department_choices=constants.department_choices, designation_choices=constants.designation_choices)


@manager_bp.route('/create', methods=('GET', 'POST'))
@utils.role_required(["admin"])
def create_manager():
    if not utils.get_manager_role():
        flash("You need to first create a role with 'manager'", 'danger')
        if current_user.role == "manager":
            return redirect(url_for('manager_bp.manager_dashboard'))
        return redirect(url_for('admin_bp.admin_dashboard'))
    form = ManagerForm()
    if form.validate_on_submit():
        if utils.is_email_exists(request.form['email']):
            flash('Email must be unique.', 'danger')
        elif utils.is_phonenumber_exists(request.form['phone']):
            flash('Phone number must be unique.', 'danger')
        else:
            mongo.db.users.insert_one(
                {'name': request.form['name'], 'email': request.form['email'], 'phone': request.form['phone'],
                 'password': request.form['password'], 'hired_date': request.form['hired_date'],
                 'role_id': utils.get_manager_role()['_id']})
            if current_user.role == "manager":
                return redirect(url_for('manager_bp.manager_dashboard'))
            return redirect(url_for('admin_bp.admin_dashboard'))
    return render_template('manager_create.html', form=form)


@employee_bp.route('/dashboard', methods=('GET', 'POST'))
@utils.role_required(["employee"])
def employee_dashboard():
    user_id = current_user.id
    user_id = ObjectId(user_id)
    user = mongo.db.users.find_one({"_id": user_id})
    if user:
        user['_id'] = str(user['_id'])
        if user.get('manager'):
            user['manager'] = mongo.db.users.find_one({"_id": user["manager"]})["name"]
        else:
            user["manager"] = ""
        return render_template('employee_dashboard.html', user=user)
    flash('Employee details not found.', 'danger')
    return redirect(url_for('login_bp.login'))


@employee_bp.route('/detail/<employee_id>', methods=('GET', 'POST'))
@utils.role_required(["admin", "manager"])
def employee_detail(employee_id):
    form = EmployeeForm()
    form.manager.choices = [(manager.get('_id'), manager.get('name')) for manager in utils.get_managers()]
    if ObjectId.is_valid(employee_id):
        employee = mongo.db.users.find_one({'_id': ObjectId(employee_id)})
        if employee:
            return render_template('employee_detail.html', form=form, employee=employee)
    flash('Employee details not found.', 'danger')
    return redirect(url_for('login_bp.login'))


@employee_bp.route('/create', methods=('GET', 'POST'))
@utils.role_required(["admin", "manager"])
def create_employee():
    if not utils.get_employee_role():
        flash("You need to first create a role with 'employee'", 'danger')
        if current_user.role == "manager":
            return redirect(url_for('manager_bp.manager_dashboard'))
        return redirect(url_for('admin_bp.admin_dashboard'))
    # role_detail = utils.get_role_data(current_user.role)
    # if not 'admin_access' in role_detail.get('permission_names', []) and not 'add_employee' in role_detail.get('permisision_names', []):
    #     flash("You don't have permission to access this page.", 'danger')
    #     return redirect(url_for('login_bp.login'))
    form = EmployeeForm()
    form.manager.choices = [(manager.get('_id'), manager.get('name')) for manager in utils.get_managers()]
    if form.validate_on_submit():
        if utils.is_email_exists(request.form['email']):
            flash('Email must be unique.', 'danger')
        elif utils.is_phonenumber_exists(request.form['phone']):
            flash('Phone number must be unique.', 'danger')
        else:
            mongo.db.users.insert_one(
                {'name': request.form['name'], 'email': request.form['email'], 'phone': request.form['phone'],
                 'password': request.form['password'], 'designation': request.form['designation'], 'department': request.form['department'],
                 'manager': ObjectId(request.form['manager']), 'hired_date': request.form['hired_date'],
                 'role_id': utils.get_employee_role()['_id']})
            if current_user.role == "manager":
                return redirect(url_for('manager_bp.manager_dashboard'))
            return redirect(url_for('admin_bp.admin_dashboard'))
    return render_template('employee_create.html', form=form)


@employee_bp.route('/edit/<employee_id>', methods=('GET', 'POST'))
@utils.role_required(["admin", "manager"])
def edit_employee(employee_id):
    form = EmployeeForm()
    form.manager.choices = [(manager.get('_id'), manager.get('name')) for manager in utils.get_managers()]
    if request.method == 'POST':
        new_data = {
            'name': request.form['name'],
            'email': request.form['email'],
            'phone': request.form['phone'],
            'designation': request.form['designation'],
            'department': request.form['department'],
            'manager': ObjectId(request.form['manager']),
            'hired_date': request.form['hired_date']
        }
        mongo.db.users.update_one({'_id': ObjectId(employee_id)}, {'$set': new_data})
        if current_user.role == "manager":
            return redirect(url_for('manager_bp.manager_dashboard'))
        return redirect(url_for('admin_bp.admin_dashboard'))
    else:
        employee = mongo.db.users.find_one({'_id': ObjectId(employee_id)})

users/templates/admin_dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Employee Dashboard</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<!--    <link rel="stylesheet" href="css/styles.css">-->
    <style>
        /* Custom CSS for font color */
        .employee-dashboard-title {
            color: blue;
        }
        /* Style for the logout button */
        .logout-button {
            position: absolute;
            top: 10px;
            right: 10px;
        }
        .small-search-form {
            max-width: 300px;
        }
        .small-search-button {
            width: 100px;
        }
                .search-filter {
            display: flex;
            justify-content: flex-end;
        }
    </style>
</head>
<body style="background-color: #fff;">
    <div class="container mt-5">
        <a href="{{ url_for('login_bp.logout') }}" class="btn btn-danger logout-button">Logout</a>
        <div class="col-md-12 text-center">
            <h2 class="mb-4 employee-dashboard-title">Employee Management | Role: {{current_user.role|capitalize}}</h2>
        </div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
        <div class="card">
            <div class="card-body">
                <br>
                <h3><b>Employees</b></h3>
                <br>
                <div class="search-filter">
                    <form method="POST" action="{{ url_for('employee_bp.search_employees') }}" class="small-search-form input-group">
                        <input type="text" class="form-control" name="search" placeholder="Search...">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary small-search-button">Search</button>
                        </div>
                    </form>
                    <button type="button" class="btn btn-secondary ml-2" data-toggle="modal" data-target="#filterModal">Filter</button>
                </div>
        <div class="row">
            <div class="col-md-6 text-right">
                <a href="{{ url_for('employee_bp.create_employee') }}" class="btn btn-primary">Create Employee</a>
                <a href="{{ url_for('export_bp.export', export_type='csv') }}" class="btn btn-success">Export CSV</a>
                <a href="{{ url_for('export_bp.export', export_type='xlsx') }}" class="btn btn-success">Export XLSX</a>
                <a href="{{ url_for('export_bp.export', export_type='json') }}" class="btn btn-success">Export JSON</a>
            </div>
<br>
            <!-- Modal for employee filter -->
    <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="filterModalLabel">Filter Employees</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="{{ url_for('employee_bp.filter_employees') }}">
                        <div class="form-group">
                            <label for="designation">Designation</label>
                            <select class="form-control" id="designation" name="designation">
                                <option value="">Select Designation</option>
                                {% for each in designation_choices %}
                                <option value="{{each[0]}}">{{each[1]}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="department">Department</label>
                            <select class="form-control" id="department" name="department">
                                <option value="">Select Department</option>
                                {% for each in department_choices %}
                                <option value="{{each[0]}}">{{each[1]}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Apply Filter</button>
                    </form>
                </div>
            </div>
        </div>
            </div>
        <br>
        <!-- Employee table -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Manager</th>
                    <th>Designation</th>
                    <th>Department</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td><a href="{{ url_for('employee_bp.employee_detail', employee_id=employee._id) }}">{{ employee.name }}</a></td>
                    <td>{{ employee.email }}</td>
                    <td>{{ employee.phone }}</td>
                    <td>{{ employee.manager_name }}</td>
                    <td>{{ employee.designation }}</td>
                    <td>{{ employee.department }}</td>
                    <td>
                        <a href="{{ url_for('employee_bp.edit_employee', employee_id=employee._id) }}" class="btn btn-warning btn-sm">Edit</a>
                        <a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirmationModal {{ employee._id }}" data-employee-id="{{ employee._id }}">Delete</a>

                    </td>
                </tr>
                <div class="modal fade" id="confirmationModal {{ employee._id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel {{ employee._id }}" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmationModalLabel {{ employee._id }}">Confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this employee?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <a id="confirmDelete" class="btn btn-danger" href="{{ url_for('employee_bp.delete_employee', employee_id=employee._id) }}">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
                {% endfor %}
            </tbody>
        </table>
    </div>
        <br>
        <h3><b>Managers</b></h3>
        <br>
            <!-- Add a form for manager filtering if needed -->
        <div class="row">
            <div class="col-md-6 text-left">
                <a href="{{ url_for('manager_bp.create_manager') }}" class="btn btn-primary">Create Manager</a>
        </div>
                <br><br>
        <!-- Manager table -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                {% for manager in managers %}
                <tr>
                    <td>{{ manager.name }}</td>
                    <td>{{ manager.phone }}</td>
                    <td>{{ manager.email }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
            </div>
                        <br>
        <h3><b>Permissions</b></h3>
                        <div class="row">

           <div class="col-md-6 text-left">
                <a href="{{ url_for('permissions_bp.create_permission') }}" class="btn btn-primary">Create Permission</a>
        </div>
                            </div>
                <br>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Permission</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for permission in permissions %}
                <tr>
                    <td>{{ permission.name }}</td>
                    <td>
                    <a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirmationPermissionModal{{ permission._id }}" data-permission-id="{{ permission._id }}">Delete</a>
                    </td>
                </tr>
                            <div class="modal fade" id="confirmationPermissionModal{{ permission._id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationPermissionModalLabel{{ permission._id }}" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmationPermissionModalLabel{{ permission._id }}">Confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this permission?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <a id="confirmPermissionDelete" class="btn btn-danger" href="{{ url_for('permissions_bp.delete_permission', permission_id=permission._id) }}">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
                {% endfor %}
            </tbody>
        </table>
                                      <br>
        <h3><b>Roles</b></h3>
                        <div class="row">
           <div class="col-md-6 text-left">
                <a href="{{ url_for('roles_bp.create_role') }}" class="btn btn-primary">Create Role</a>
        </div>
                            </div>
                <br>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Role</th>
                    <th>Permissions</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            {% for role in roles %}
            <tr>
                <td>{{ role.name }}</td>
                <td>{{ role.permission_names }}</td>
                <td>
                    <a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirmationRoleModal{{ role._id }}" data-role-id="{{ role._id }}">Delete</a>
                </td>
            </tr>
            <div class="modal fade" id="confirmationRoleModal{{ role._id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationRoleModalLabel{{ role._id }}" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmationRoleModalLabel{{ role._id }}">Confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this role?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <a id="confirmRoleDelete" class="btn btn-danger" href="{{ url_for('roles_bp.delete_role', role_id=role._id) }}">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>




</body>
</html>

users/templates/manager_dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Employee Dashboard</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<!--    <link rel="stylesheet" href="css/styles.css">-->
    <style>
        /* Custom CSS for font color */
        .employee-dashboard-title {
            color: blue;
        }
        /* Style for the logout button */
        .logout-button {
            position: absolute;
            top: 10px;
            right: 10px;
        }
        .small-search-form {
            max-width: 300px;
        }
        .small-search-button {
            width: 100px;
        }
                .search-filter {
            display: flex;
            justify-content: flex-end;
        }
    </style>
</head>
<body style="background-color: #fff;">
    <div class="container mt-5">
        <a href="{{ url_for('login_bp.logout') }}" class="btn btn-danger logout-button">Logout</a>
        <div class="col-md-12 text-center">
            <h2 class="mb-4 employee-dashboard-title">Employee Management | Role: {{current_user.role|capitalize}}</h2>
        </div>
        <div class="card">
            <div class="card-body">
                <br>
                <h3><b>Employees</b></h3>
                <br>
                <div class="search-filter">
                    <form method="POST" action="{{ url_for('employee_bp.search_employees') }}" class="small-search-form input-group">
                        <input type="text" class="form-control" name="search" placeholder="Search...">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary small-search-button">Search</button>
                        </div>
                    </form>
                    <button type="button" class="btn btn-secondary ml-2" data-toggle="modal" data-target="#filterModal">Filter</button>
                </div>
        <div class="row">
            <div class="col-md-6 text-right">
                <a href="{{ url_for('employee_bp.create_employee') }}" class="btn btn-primary">Create Employee</a>
                <a href="{{ url_for('export_bp.export', export_type='csv') }}" class="btn btn-success">Export CSV</a>
                <a href="{{ url_for('export_bp.export', export_type='xlsx') }}" class="btn btn-success">Export XLSX</a>
                <a href="{{ url_for('export_bp.export', export_type='json') }}" class="btn btn-success">Export JSON</a>
            </div>
<br>
            <!-- Modal for employee filter -->
    <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="filterModalLabel">Filter Employees</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" action="{{ url_for('employee_bp.filter_employees') }}">
                        <div class="form-group">
                            <label for="designation">Designation</label>
                            <select class="form-control" id="designation" name="designation">
                                <option value="">Select Designation</option>
                                {% for each in designation_choices %}
                                <option value="{{each[0]}}">{{each[1]}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="department">Department</label>
                            <select class="form-control" id="department" name="department">
                                <option value="">Select Department</option>
                                {% for each in department_choices %}
                                <option value="{{each[0]}}">{{each[1]}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Apply Filter</button>
                    </form>
                </div>
            </div>
        </div>
            </div>
        <br>
        <!-- Employee table -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Manager</th>
                    <th>Designation</th>
                    <th>Department</th>
                    <th>Action</th> <!-- Column for Edit and Delete buttons -->
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td><a href="{{ url_for('employee_bp.employee_detail', employee_id=employee._id) }}">{{ employee.name }}</a></td>
                    <td>{{ employee.email }}</td>
                    <td>{{ employee.phone }}</td>
                    <td>{{ employee.manager_name }}</td>
                    <td>{{ employee.designation }}</td>
                    <td>{{ employee.department }}</td>
                    <td>
                        <a href="{{ url_for('employee_bp.edit_employee', employee_id=employee._id) }}" class="btn btn-warning btn-sm">Edit</a>
                        <a href="#" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirmationModal {{ employee._id }}" data-employee-id="{{ employee._id }}">Delete</a>

                    </td>
                </tr>
                <div class="modal fade" id="confirmationModal {{ employee._id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel {{ employee._id }}" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="confirmationModalLabel {{ employee._id }}">Confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this employee?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <a id="confirmDelete" class="btn btn-danger" href="{{ url_for('employee_bp.delete_employee', employee_id=employee._id) }}">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
                {% endfor %}
            </tbody>
        </table>
    </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>




</body>
</html>